// packages/react-docx-preview/src/DocxViewer.tsx
// React DOCX viewer component — WPS-style toolbar, pager, zoom, thumbnails and
// page corners. The whole chrome lives in this one file, mirroring
// packages/vue-docx-preview/src/DocxViewer.vue: reactive state and the DOM work
// that can't be expressed declaratively are in ./hooks/useDocViewer, the icons
// in ./components/icons. The document is fetched from the `url` prop (optionally
// via `customRequest`, e.g. for authenticated endpoints) and re-renders when it
// changes; initialScale/showThumbs/renderOptions describe the initial mount
// (like viewer.html's URL params).
import { useEffect, useRef, useState } from 'react'
import type { CSSProperties, ReactNode } from 'react'
import type { Options } from '@apollo-design/docx-preview'
import { useDocViewer } from './hooks/useDocViewer'
import type { DocxCustomRequest } from './hooks/useDocViewer'
import { IconThumbs } from './components/icons/IconThumbs'
import { IconPrevPage } from './components/icons/IconPrevPage'
import { IconNextPage } from './components/icons/IconNextPage'
import { IconZoomOut } from './components/icons/IconZoomOut'
import { IconZoomIn } from './components/icons/IconZoomIn'
import { IconChevronDown } from './components/icons/IconChevronDown'
import { IconOpenFile } from './components/icons/IconOpenFile'
import { IconDownload } from './components/icons/IconDownload'
import './styles/viewer.css'

const SCALES = ['fit', '0.5', '0.75', '1', '1.25', '1.5', '2']

export interface DocxViewerProps {
  /** 文档地址,默认 GET 读取;变化即重新加载。为空(null/空串)时显示空态 */
  url?: string | null
  /** 自定义请求(可附加鉴权头等),返回文档数据;缺省用 fetch GET */
  customRequest?: DocxCustomRequest
  /** document name for the download button; defaults to the URL's last path segment */
  name?: string
  /** 'fit' | number (0.75, 75, …) — initial zoom; mount-time only */
  initialScale?: 'fit' | number
  /** initial thumbnail sidebar visibility; mount-time only */
  showThumbs?: boolean
  /** library render options, merged over { paginate, experimental } */
  renderOptions?: Partial<Options>
  /** 无文档时的占位内容(Vue 版 `#empty` 插槽的对应物) */
  empty?: ReactNode
  className?: string
  style?: CSSProperties
  onRendered?: (result: unknown) => void
  onError?: (error: unknown) => void
}

export function DocxViewer({
  url = null,
  customRequest,
  name,
  initialScale,
  showThumbs,
  renderOptions,
  empty,
  className,
  style,
  onRendered,
  onError,
}: DocxViewerProps) {
  // ── DOM refs ──
  const stage = useRef<HTMLElement>(null)
  const docBox = useRef<HTMLDivElement>(null)
  const thumbs = useRef<HTMLElement>(null)
  const fileInput = useRef<HTMLInputElement>(null)

  const api = useDocViewer(
    { stage, docBox, thumbs },
    { initialScale, showThumbs, renderOptions, onRendered, onError },
  )

  // customRequest is a function prop — read it through a ref so an inline
  // lambda doesn't retrigger the load on every render.
  const requestRef = useRef(customRequest)
  requestRef.current = customRequest

  const hasUrl = typeof url === 'string' && url.length > 0
  const showEmpty = !hasUrl && !api.loading

  // ── 密码弹窗（加密文档） ──
  const [passwordValue, setPasswordValue] = useState('')
  const passwordInput = useRef<HTMLInputElement>(null)
  const prompt = api.passwordPrompt
  useEffect(() => {
    if (!prompt) return
    // 打开弹窗、以及密码错误后回到输入态时，清空并重新聚焦
    setPasswordValue('')
    passwordInput.current?.focus()
  }, [prompt])

  async function onPasswordSubmit(event: React.FormEvent) {
    event.preventDefault()
    if (!passwordValue) {
      passwordInput.current?.focus()
      return
    }
    await api.submitPassword(passwordValue)
    passwordInput.current?.focus()
  }

  useEffect(() => {
    if (hasUrl && url) api.openUrl(url, requestRef.current, name)
    else api.close()
    // openUrl/close read the latest props through refs, so re-running only when
    // the document identity changes matches the Vue port's `watch([url, name])`.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [url, name])

  function onFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const input = event.currentTarget
    const file = input.files && input.files[0]
    if (file) api.open(file)
    // Reset so picking the same file twice still fires change.
    input.value = ''
  }

  function onJump(event: React.SyntheticEvent<HTMLInputElement>) {
    const input = event.currentTarget
    api.jumpToPage(input.value)
    input.blur()
  }

  function onThumbClick(event: React.MouseEvent) {
    const item = (event.target as HTMLElement).closest('.thumb')
    if (item) api.goToPage(Number(item.getAttribute('data-page')))
  }

  return (
    <div className={className ? `docx-viewer ${className}` : 'docx-viewer'} style={style}>
      <header className="toolbar" hidden={!api.docLoaded}>
        <div className="toolbar-left">
          <button
            className={api.thumbsShown ? 'tbtn active' : 'tbtn'}
            type="button"
            title="缩略图"
            disabled={!api.docLoaded || api.pageCount <= 1}
            onClick={api.toggleThumbs}
          >
            <IconThumbs />
          </button>
          <span className="toolbar-divider"></span>
          <span className="pager" hidden={!api.pagerShown}>
            <button
              className="tbtn"
              type="button"
              title="上一页"
              disabled={!api.canPrev}
              onClick={() => api.goToPage(api.currentPage - 1)}
            >
              <IconPrevPage />
            </button>
            <span className="page-info">
              {/* Uncontrolled + keyed by page: typing is free-form, and a page
                  change remounts the input with the fresh page number. */}
              <input
                key={api.currentPage}
                className="page-input"
                type="number"
                min={1}
                step={1}
                defaultValue={api.pageCount > 0 ? api.currentPage + 1 : ''}
                aria-label="当前页码"
                onKeyDown={(e) => {
                  if (e.key === 'Enter') onJump(e)
                }}
                onBlur={onJump}
              />
              <span className="page-total">/ {api.pageCount > 0 ? api.pageCount : '–'}</span>
            </span>
            <button
              className="tbtn"
              type="button"
              title="下一页"
              disabled={!api.canNext}
              onClick={() => api.goToPage(api.currentPage + 1)}
            >
              <IconNextPage />
            </button>
          </span>
        </div>

        <div className="toolbar-center">
          <div className="zoom-group">
            <button
              className="tbtn"
              type="button"
              title="缩小"
              disabled={!api.canZoomOut}
              onClick={() => api.zoomStep(-1)}
            >
              <IconZoomOut />
            </button>
            <div className="scale-select">
              <button
                className="tbtn scale-display"
                type="button"
                onClick={(e) => {
                  e.stopPropagation()
                  api.setDropdownOpen(!api.dropdownOpen)
                }}
              >
                <span>{api.scaleLabel}</span>
                <IconChevronDown />
              </button>
              <div className="dropdown" hidden={!api.dropdownOpen}>
                {SCALES.map((s) => (
                  <button
                    key={s}
                    type="button"
                    className={
                      (api.scaleMode === 'fit' && s === 'fit') || String(api.scaleMode) === s
                        ? 'selected'
                        : undefined
                    }
                    onClick={() => api.setScale(s)}
                  >
                    {s === 'fit' ? '适应宽度' : Math.round(parseFloat(s) * 100) + '%'}
                  </button>
                ))}
              </div>
            </div>
            <button
              className="tbtn"
              type="button"
              title="放大"
              disabled={!api.canZoomIn}
              onClick={() => api.zoomStep(1)}
            >
              <IconZoomIn />
            </button>
          </div>
        </div>

        <div className="toolbar-right">
          <button
            className="tbtn"
            type="button"
            title="打开文档"
            onClick={() => fileInput.current?.click()}
          >
            <IconOpenFile />
          </button>
          <button
            className="tbtn"
            type="button"
            title="下载文档"
            disabled={!api.docLoaded}
            onClick={api.download}
          >
            <IconDownload />
          </button>
          <input ref={fileInput} type="file" accept=".docx" hidden onChange={onFileChange} />
        </div>
      </header>

      <div className="error-banner" hidden={!api.error}>
        <strong>{api.error?.title}</strong>
        <span>{api.error?.detail}</span>
      </div>

      <div className="body">
        <aside
          ref={thumbs}
          className="thumbs"
          hidden={!api.thumbsShown}
          aria-label="页面缩略图"
          onClick={onThumbClick}
        />

        <main ref={stage} className="stage">
          <div className="loading" hidden={!api.loading}>
            <div className="spinner"></div>
            <p>加载中…</p>
          </div>

          {/* The library renders into this box; hidden while there is no URL. */}
          <div ref={docBox} className="document" hidden={!hasUrl} />

          {showEmpty && (
            <div className="empty">
              {empty ?? (
                <div className="empty-default">
                  <p>暂无预览文档</p>
                </div>
              )}
            </div>
          )}
        </main>
      </div>

      {/* 加密文档：密码弹窗 */}
      {prompt && (
        <div className="password-modal" role="dialog" aria-modal="true" aria-label="文档需要密码">
          <form className="password-card" onSubmit={onPasswordSubmit}>
            <h2 className="password-title">文档已加密</h2>
            <p className="password-hint">「{prompt.fileName}」需要密码才能打开。</p>
            <input
              ref={passwordInput}
              className="password-input"
              type="password"
              autoComplete="current-password"
              placeholder="请输入文档密码"
              value={passwordValue}
              disabled={prompt.busy}
              onChange={(event) => setPasswordValue(event.currentTarget.value)}
              onKeyDown={(event) => {
                if (event.key === 'Escape') api.cancelPassword()
              }}
            />
            <p className="password-error" hidden={!prompt.wrong}>
              密码不正确，请重试。
            </p>
            <div className="password-actions">
              <button
                className="password-btn"
                type="button"
                disabled={prompt.busy}
                onClick={api.cancelPassword}
              >
                取消
              </button>
              <button className="password-btn primary" type="submit" disabled={prompt.busy}>
                {prompt.busy ? '解密中…' : '确定'}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  )
}

export default DocxViewer

// packages/svelte-docx-preview/src/DocxViewer.svelte
<script lang="ts">
  // Svelte 5 DOCX viewer component — WPS-style toolbar, pager, zoom,
  // thumbnails and page corners. The whole chrome lives in this one file
  // (mirroring the vue/react wrappers); reactive state and the DOM work that
  // can't be expressed declaratively are in ./composables/useDocViewer.svelte,
  // the icons in ./components/icons.
  import { untrack } from 'svelte'
  import { useDocViewer } from './composables/useDocViewer.svelte'
  import type { DocxViewerProps } from './types'
  import IconThumbs from './components/icons/IconThumbs.svelte'
  import IconPrevPage from './components/icons/IconPrevPage.svelte'
  import IconNextPage from './components/icons/IconNextPage.svelte'
  import IconZoomOut from './components/icons/IconZoomOut.svelte'
  import IconZoomIn from './components/icons/IconZoomIn.svelte'
  import IconChevronDown from './components/icons/IconChevronDown.svelte'
  import IconOpenFile from './components/icons/IconOpenFile.svelte'
  import IconDownload from './components/icons/IconDownload.svelte'
  import './styles/viewer.css'

  let {
    url = null,
    customRequest,
    name,
    initialScale,
    showThumbs,
    renderOptions,
    empty,
    class: className = '',
    onRendered,
    onError,
  }: DocxViewerProps = $props()

  const SCALES = ['fit', '0.5', '0.75', '1', '1.25', '1.5', '2']

  // Element refs (bind:this fills them after mount).
  let stage = $state<HTMLElement>()
  let docBox = $state<HTMLDivElement>()
  let thumbs = $state<HTMLElement>()
  let fileInput = $state<HTMLInputElement>()

  const api = useDocViewer(
    { stage: () => stage, docBox: () => docBox, thumbs: () => thumbs },
    // Getters keep the options live: the composable reads them per call, so a
    // parent that swaps a callback (or renderOptions) isn't stuck with the
    // initial one. `initialScale` / `showThumbs` are mount-time only by design.
    {
      get initialScale() {
        return initialScale
      },
      get showThumbs() {
        return showThumbs
      },
      get renderOptions() {
        return renderOptions
      },
      get onRendered() {
        return onRendered
      },
      get onError() {
        return onError
      },
    },
  )

  const hasUrl = $derived(typeof url === 'string' && url.length > 0)
  const showEmpty = $derived(!hasUrl && !api.loading)

  // ── 密码弹窗（加密文档） ──
  let passwordValue = $state('')
  let passwordInput = $state<HTMLInputElement>()

  $effect(() => {
    if (!api.passwordPrompt) return
    // 打开弹窗、以及密码错误后回到输入态时，清空并重新聚焦
    passwordValue = ''
    passwordInput?.focus()
  })

  async function onPasswordSubmit(event: SubmitEvent) {
    event.preventDefault()
    if (!passwordValue) {
      passwordInput?.focus()
      return
    }
    await api.submitPassword(passwordValue)
    passwordInput?.focus()
  }

  // 文档身份变化即重新加载（对齐 vue 版 `watch([url, name])`）。
  // untrack：渲染过程会读元素引用，但这些引用不属于「文档身份」，
  // 不能因为它们挂载时被赋值就再触发一次加载。
  $effect(() => {
    const nextUrl = url
    const nextName = name
    const shouldLoad = hasUrl
    untrack(() => {
      if (shouldLoad && nextUrl) api.openUrl(nextUrl, customRequest, nextName)
      else api.close()
    })
  })

  function onFileChange(event: Event) {
    const input = event.currentTarget as HTMLInputElement
    const file = input.files?.[0]
    if (file) api.open(file)
    // Reset so picking the same file twice still fires change.
    input.value = ''
  }

  function onJump(event: Event) {
    const input = event.currentTarget as HTMLInputElement
    api.jumpToPage(input.value)
    input.blur()
  }

  function onJumpKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') onJump(event)
  }

  function onThumbClick(event: MouseEvent) {
    const item = (event.target as HTMLElement).closest('.thumb')
    if (item) api.goToPage(Number(item.getAttribute('data-page')))
  }
</script>

<div class={className ? `docx-viewer ${className}` : 'docx-viewer'}>
  <header class="toolbar" hidden={!api.docLoaded}>
    <div class="toolbar-left">
      <button
        class={api.thumbsShown ? 'tbtn active' : 'tbtn'}
        type="button"
        title="缩略图"
        disabled={!api.docLoaded || api.pageCount <= 1}
        onclick={() => api.toggleThumbs()}
      >
        <IconThumbs />
      </button>
      <span class="toolbar-divider"></span>
      <span class="pager" hidden={!api.pagerShown}>
        <button
          class="tbtn"
          type="button"
          title="上一页"
          disabled={!api.canPrev}
          onclick={() => api.goToPage(api.currentPage - 1)}
        >
          <IconPrevPage />
        </button>
        <span class="page-info">
          <!-- keyed by page: a page change remounts the input with the fresh number -->
          {#key api.currentPage}
            <input
              class="page-input"
              type="number"
              min="1"
              step="1"
              value={api.pageCount > 0 ? api.currentPage + 1 : ''}
              aria-label="当前页码"
              onkeydown={onJumpKeydown}
              onblur={onJump}
            />
          {/key}
          <span class="page-total">/ {api.pageCount > 0 ? api.pageCount : '–'}</span>
        </span>
        <button
          class="tbtn"
          type="button"
          title="下一页"
          disabled={!api.canNext}
          onclick={() => api.goToPage(api.currentPage + 1)}
        >
          <IconNextPage />
        </button>
      </span>
    </div>

    <div class="toolbar-center">
      <div class="zoom-group">
        <button
          class="tbtn"
          type="button"
          title="缩小"
          disabled={!api.canZoomOut}
          onclick={() => api.zoomStep(-1)}
        >
          <IconZoomOut />
        </button>
        <div class="scale-select">
          <button
            class="tbtn scale-display"
            type="button"
            onclick={(event) => {
              event.stopPropagation()
              api.toggleDropdown()
            }}
          >
            <span>{api.scaleLabel}</span>
            <IconChevronDown />
          </button>
          <div class="dropdown" hidden={!api.dropdownOpen}>
            {#each SCALES as scale (scale)}
              <button
                type="button"
                class={(api.scaleMode === 'fit' && scale === 'fit') ||
                String(api.scaleMode) === scale
                  ? 'selected'
                  : undefined}
                onclick={() => api.setScale(scale)}
              >
                {scale === 'fit' ? '适应宽度' : Math.round(parseFloat(scale) * 100) + '%'}
              </button>
            {/each}
          </div>
        </div>
        <button
          class="tbtn"
          type="button"
          title="放大"
          disabled={!api.canZoomIn}
          onclick={() => api.zoomStep(1)}
        >
          <IconZoomIn />
        </button>
      </div>
    </div>

    <div class="toolbar-right">
      <button class="tbtn" type="button" title="打开文档" onclick={() => fileInput?.click()}>
        <IconOpenFile />
      </button>
      <button class="tbtn" type="button" title="下载文档" disabled={!api.docLoaded} onclick={api.download}>
        <IconDownload />
      </button>
      <input bind:this={fileInput} type="file" accept=".docx" hidden onchange={onFileChange} />
    </div>
  </header>

  <div class="error-banner" hidden={!api.error}>
    <strong>{api.error?.title}</strong>
    <span>{api.error?.detail}</span>
  </div>

  <div class="body">
    <!-- 缩略图侧栏的点击由内部 .thumb 命中测试处理（与 vue/react 版一致），
         它不是可聚焦控件，因此关掉 a11y 的非交互元素告警。 -->
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <aside bind:this={thumbs} class="thumbs" hidden={!api.thumbsShown} aria-label="页面缩略图" onclick={onThumbClick}></aside>

    <main bind:this={stage} class="stage">
      <div class="loading" hidden={!api.loading}>
        <div class="spinner"></div>
        <p>加载中…</p>
      </div>

      <!-- The library renders into this box; hidden while there is no URL. -->
      <div bind:this={docBox} class="document" hidden={!hasUrl}></div>

      {#if showEmpty}
        <div class="empty">
          {#if empty}
            {@render empty()}
          {:else}
            <div class="empty-default"><p>暂无预览文档</p></div>
          {/if}
        </div>
      {/if}
    </main>
  </div>

  <!-- 加密文档：密码弹窗 -->
  {#if api.passwordPrompt}
    <div class="password-modal" role="dialog" aria-modal="true" aria-label="文档需要密码">
      <form class="password-card" onsubmit={onPasswordSubmit}>
        <h2 class="password-title">文档已加密</h2>
        <p class="password-hint">「{api.passwordPrompt.fileName}」需要密码才能打开。</p>
        <input
          bind:this={passwordInput}
          bind:value={passwordValue}
          class="password-input"
          type="password"
          autocomplete="current-password"
          placeholder="请输入文档密码"
          disabled={api.passwordPrompt.busy}
          onkeydown={(event) => {
            if (event.key === 'Escape') api.cancelPassword()
          }}
        />
        <p class="password-error" hidden={!api.passwordPrompt.wrong}>密码不正确，请重试。</p>
        <div class="password-actions">
          <button class="password-btn" type="button" disabled={api.passwordPrompt.busy} onclick={api.cancelPassword}>
            取消
          </button>
          <button class="password-btn primary" type="submit" disabled={api.passwordPrompt.busy}>
            {api.passwordPrompt.busy ? '解密中…' : '确定'}
          </button>
        </div>
      </form>
    </div>
  {/if}
</div>
